version: '3.8'
services:
  mydb:
    container_name: pg-shop
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shopping
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shopping'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes: 
      - db:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./
    depends_on:
      mydb:
        condition: service_healthy
    ports:
      - 2001:2001
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: shopping
    links:
      - mydb
    volumes:
      - './:/src'
    
volumes:
  db:
    driver: local